Show payloadExtraction warning only when null or undefined
nuxt/nuxt pull request #18516
Opened 2023-01-25 13:49 UTC by HyunseungLee-Travis

### 🔗 Linked issue

No linked issue.

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This is only a minor change and I am not sure if it is a good one.

This change should be made because when users sets `experimental.payloadExtraction` to `true` on purpose, they are hinting that either they are doing this on purpose or wanting the warnings to be gone. 

This code change only changes the code so that if the `enabled` property is `undefined` (meaning the user did not set any configuration), it shows the warnings, but if the user sets it to `true` there will be no warnings.

### 🧪 Tests / Examples

![notdefined](https://user-images.githubusercontent.com/78584173/214580321-6d08a6dd-95de-4236-b8e2-4cbf843e6300.png)

![setfalse](https://user-images.githubusercontent.com/78584173/214580335-44fbf33a-97fe-49ff-807c-d64dda51ec79.png)
![settrue](https://user-images.githubusercontent.com/78584173/214580341-f51ff416-016b-4499-87e2-2cb4911e9057.png)

2023-01-25 15:56 UTC, danielroe commented on packages/schema/src/config/experimental.ts
> +        if (enabled == null) {
I prefer to make it explicit:

```suggestion
        if (enabled === null || enabled === undefined) {
```

2023-01-25 15:56 UTC, danielroe approved these changes
This is a nice change, thank you!

2023-01-25 16:08 UTC, danielroe requested changes, later dismissed
Oops, my apologies; I forgot how we are doing this. In fact we set this here:

https://github.com/nuxt/nuxt.js/blob/6e78f9dbb03a059814d1284511f732b901dea4f6/packages/nuxi/src/commands/build.ts#L30-L34

So we don't want to show warning always if it is null or undefined because it is only on prerendering that it is in fact enabled, and in that case it is because it is _set_ to `true`.

2023-03-13 09:50 UTC, pi0 approved these changes

2023-03-13 11:06 UTC, merged