fix: use "import.meta.url" for internal require
nuxt/nuxt pull request #18917
Opened 2023-02-09 12:52 UTC by kettanaito

### 🔗 Linked issue

There's no related issue currently open in this repo. Given the scope of this change, I propose to treat this pull request as both the issue report and the proposed resolution. 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

The internal usage of `Module.createRequire()` in `cjs.ts` is incorrect. Per [Node.js documentation](https://nodejs.org/api/module.html#modulecreaterequirefilename), the `filename` argument must be a _file name_. Passing `process.cwd()` does not yield a file name but a _directory path_. 

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-02-09 12:55 UTC, kettanaito commented on packages/nuxi/src/utils/cjs.ts
> +const _require = createRequire(import.meta.url)
Despite the name `cjs`, I can clearly see that Nuxt ships this chunk as a shared module imported in `cli.mjs` so I assume this is meant to run as ESM.

Let me know if this is a wrong assumption and I should use `__filename` here instead.

2023-02-13 22:54 UTC, pi0 requested changes
This doesn't look a fix. `import.meta.url` in the context of `nuxi` package, refers to where the (zero dependencies) module exists. While we need to require/import from user's directory which we change cwd to rootDir

2023-02-14 10:51 UTC, kettanaito commented
@pi0, could you please share more context on why you need to force this require from the user's root? All that the custom `filename` will affect is the lookup tree of any dependencies you require via this created `require` function. By specifying nuxi CLI as the filename, Node will be able to resolve dependencies even in stores that do not have flat structure, like PNPM. Forcing require's from the root break that, as PNPM doesn't install 4th party dependencies in the root-level node_modules (nuxi (3rd) -> `createRequire()` -> always requires 4th-party dependencies). That's the reason #14146 happens. 

From my limited understanding of nuxi, there isn't any change to the behavior of this require apart from allowing Node to work its way up the dependency tree to resolve 4th-party dependencies, which would be correct.

2023-03-06 11:40 UTC, pi0 commented
Nuxi CLI is a zero-dependency package that can also be installed globally. Only use case of internal `_require` inside nuxi, passes and overrides with explicit search paths ([in `resolveModule`](https://github.com/nuxt/nuxt/blob/00087b014455b719f30cd135e3f37bceb91be879/packages/nuxi/src/utils/cjs.ts#L21)). Using `import.meta.url` isn't effective at all nor relevant to #14146. (nuxi works as expected byitself. other issues are related to nuxt builder namespace)

I would appreciate to investigate any possible changes if there is a specific issue with reproduction.

2023-03-06 11:40 UTC, closed without merging