fix(nuxt): remove cached data when onUnmounted
nuxt/nuxt pull request #20980
Opened 2023-05-21 13:36 UTC by jongmin4943

### 🔗 Linked issue

#20979

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #20979

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-05-21 13:37 UTC, jongmin4943 commented on packages/nuxt/src/app/composables/asyncData.ts
> +          if (!options.immediate || options.lazy) {
I was not sure this condition is needed because it works the same without this.

2023-05-21 13:40 UTC, jongmin4943 commented
How do I write a test for this?

2023-05-21 13:41 UTC, danielroe requested changes, later dismissed
If multiple invocations of `useAsyncData` are used (for example, in components) and one is unmounted, this would unset data for the others. It will also lead to the wrong behaviour when we're using payload extraction (for example, on a statically generated site it will remove data from the payload).

How about, instead, re-initialising the value using `options.default` when `useAsyncData` is called with `immediate: false`? (We'll still need to think about whether this is desired behaviour.)

2023-05-21 13:53 UTC, jongmin4943 commented
> If multiple invocations of `useAsyncData` are used (for example, in components) and one is unmounted, this would unset data for the others. It will also lead to the wrong behaviour when we're using payload extraction (for example, on a statically generated site it will remove data from the payload).
> 
> How about, instead, re-initialising the value using `options.default` when `useAsyncData` is called with `immediate: false`? (We'll still need to think about whether this is desired behaviour.)

I also thought about using `options.default` first actually. I'll try that. Thanks for the quick reply.

2023-05-21 15:28 UTC, jongmin4943 commented
@danielroe I was considering where to put the re-installation codes carefully. Could you check that this is okay? Thanks!

2023-06-05 21:03 UTC, danielroe reviewed
I'm not sure about the approach here, as if the state is shared with another composable it will clear it out.

What about instead updating L124 to:

```ts
if (!nuxt._asyncData[key] || !options.immediate) {
```

That way it would give a 'clean slate' for each new call of the composable but not interfere with other composable calls.

Maybe it would be valuable to add a test to the suite to cover these edge cases, as well as the original issue. Would you be able to add a test as part of the PR?

2023-06-06 15:35 UTC, jongmin4943 commented
I tried adding some more conditions at L124 before. If `!options.immediate` added, other components that have `useAsyncData` with the same key will not use cached data. It always makes new value. Even though they have the same key, they do not hold equal value.
>That way it would give a 'clean slate' for each new call of the composable but not interfere with other composable calls.
If I understand correctly, it means `options.immediate : false` will always create new value although the same key is provided?

BTW, I am not familiar with writing a test. Could you please give me some advice for a test if possible?

2023-06-11 10:49 UTC, danielroe commented
I think at the moment the best way to write a test for this is to do an e2e test in `test/basic.test.ts`. You will probably need to create some pages in `test/fixtures/basic/pages` and `test/fixtures/basic/components`. You'll use `createPage` to go to a page with some data, then navigate to another page. And you can make some assertions about what should happen.

I would make sure to test that data isn't _removed_ from a component that persists (e.g. in a layout) but that 'old' data doesn't persist when re-initialising `useAsyncData` in the new page. And confirm that the test fails on `main` branch but passes in this one.

2023-06-19 15:30 UTC, jongmin4943 commented
@danielroe I'm sorry for the late response. I was completely lost because I had a hard time writing a test haha.. I'm not sure this is the right approach. Could you please review?

2023-08-24 12:04 UTC, pi0 approved these changes

2023-08-24 12:06 UTC, merged

2023-08-24 12:06 UTC, danielroe commented
Thank you ❤️