Doc: access custom props for a NuxtLayout
nuxt/nuxt pull request #22989
Opened 2023-09-04 12:20 UTC by justinkekeocha

I documented how one can access props passed to a NuxtLayout, in the layout

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-09-04 23:13 UTC, danielroe commented on docs/3.api/2.components/3.nuxt-layout.md
> +`NuxtLayout` also accepts custom props that you may need to pass to the layout. These custom props are accessible via `attrs` in the Nuxt app.
```suggestion
`NuxtLayout` also accepts any additional props that you may need to pass to the layout. These custom props are then made accessible as attributes.
```

2023-09-04 23:13 UTC, danielroe commented on docs/3.api/2.components/3.nuxt-layout.md
> +  console.log(layoutCustomProps.title)//I am a custom layout
```suggestion
  console.log(layoutCustomProps.title) // I am a custom layout
```

2023-09-05 09:10 UTC, DamianGlowala requested changes

2023-09-05 09:10 UTC, DamianGlowala commented on docs/3.api/2.components/3.nuxt-layout.md
> +## Passing additional props
```suggestion
## Passing Additional Props
```

2023-09-05 10:05 UTC, danielroe approved these changes

2023-09-05 10:06 UTC, danielroe commented
Nice work, thank you ❤️

2023-09-05 10:09 UTC, merged