docs: unfined defineNuxtPlugin migration guide for nuxt bridge #22433
nuxt/nuxt pull request #23036
Opened 2023-09-06 09:31 UTC by adrienZ

### 🔗 Linked issue

#22433 

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

2023-09-06 12:16 UTC, wattanx approved these changes
Thank you ❤️

2023-09-06 12:24 UTC, wattanx commented on docs/6.bridge/3.bridge-composition-api.md
> ++ export default defineNuxtPlugin(nuxtApp => {
It's possible to provide an explanation similar to Nuxt 3.
https://nuxt.com/docs/migration/plugins-and-middleware#plugins

```ts
export default defineNuxtPlugin(nuxtApp => {
  // now available on `nuxtApp.$injected`
  nuxtApp.provide('injected', () => 'my injected function')

  // You can alternatively use this format, which comes with automatic type support
  return {
    provide: {
      injected: () => 'my injected function'
    }
  }
})
```

2023-09-06 12:31 UTC, wattanx reviewed
Sorry, A description of the `defineNuxtPlugin` compatible with Nuxt 3 can be found at https://nuxt.com/docs/bridge/plugins-and-middleware.

What is explained here is how to migrate from `@nuxtjs/composition-api` to Nuxt Bridge's `capi.legacy`.

2023-09-06 12:33 UTC, wattanx requested changes
I have approve it by mistake.

2023-09-28 10:17 UTC, danielroe commented
Maybe, instead of making this change to the code example, we could add a note after the example that there is a new `defineNuxtPlugin` and link to the page where it is explained?

2023-09-28 10:20 UTC, wattanx commented
> Maybe, instead of making this change to the code example, we could add a note after the example that there is a new defineNuxtPlugin and link to the page where it is explained?

I think that suggestion is a good one.

2023-11-12 14:33 UTC, wattanx approved these changes
looks good to me!

2023-11-13 11:48 UTC, danielroe approved these changes

2023-11-13 11:48 UTC, merged