feat(ci): added lychee link checker github action
nuxt/nuxt pull request #23254
Opened 2023-09-17 07:33 UTC by TechGenius7777

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This pull request adds Lychee, a Rust-based link checker that checks if the links are valid or not.

Note that the `GITHUB_TOKEN` is **only** required to increase the rate limit when checking GitHub links and does not serve any special purpose.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-09-17 10:33 UTC, TechGenius7777 commented
I messed up with the commit message / pull request title.

What should I do now?

2023-09-17 16:39 UTC, Barbapapazes commented
> I messed up with the commit message / pull request title.
> 
> What should I do now?

Hello, you can simply update your PR title since PR are squashed (so commit won't be used)!

2023-09-18 02:18 UTC, TechGenius7777 commented
> > I messed up with the commit message / pull request title.
> > What should I do now?
> 
> Hello, you can simply update your PR title since PR are squashed (so commit won't be used)!

Thank you so much!

2023-09-18 12:08 UTC, danielroe requested changes
I don't seem to have permission to push, so would you be able to address the broken links? 🙏

2023-09-18 12:34 UTC, TechGenius7777 commented
So exactly what I have to do?

Do I need to fix the broken links?

2023-09-19 17:14 UTC, TechGenius7777 commented
Pull request is ready to be merged!

2023-09-19 17:18 UTC, danielroe commented on .github/workflows/check-links.yml
> +        uses: actions/cache@v3
```suggestion
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
```

2023-09-19 17:19 UTC, danielroe commented on .github/workflows/check-links.yml
> +        uses: lycheeverse/lychee-action@v1
```suggestion
        uses: lycheeverse/lychee-action@ec7614d7605b47efb08dc370f6d0a71884cba944 # for v1.8.0
```

2023-09-19 17:20 UTC, danielroe commented on .github/workflows/check-links.yml
> +
```suggestion

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

```

2023-09-19 17:22 UTC, danielroe commented on .github/workflows/check-links.yml
> +  pull_request:
```suggestion
  push:
    paths:
      - "docs/**"
      - "*.md"
    branches:
      - main
  pull_request:
    paths:
      - "docs/**"
      - "*.md"
    branches:
      - main
```

2023-09-19 18:24 UTC, danielroe approved these changes

2023-09-19 20:22 UTC, merged

2023-09-20 02:10 UTC, TechGenius7777 commented
Thank you!