Update 2.programmatic.md
nuxt/nuxt pull request #24201
Opened 2023-11-08 21:36 UTC by MichaelJCole

Update loadNuxt documentation to latest version.  `config` option was removed.  `cwd` option is standard.

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-11-11 12:13 UTC, DamianGlowala commented on docs/3.api/5.kit/2.programmatic.md
>    **Default**: `null`
```suggestion
  **Default**: `undefined`
```

2023-11-11 12:14 UTC, DamianGlowala requested changes

2023-11-11 12:14 UTC, DamianGlowala commented on docs/3.api/5.kit/2.programmatic.md
>    **Default**: `null`
```suggestion
  **Default**: `undefined`
```

2023-11-11 12:14 UTC, DamianGlowala commented on docs/3.api/5.kit/2.programmatic.md
> +  The root directory of the Nuxt project.  The alias `rootDir` has been **Depricated**
```suggestion
  The root directory of the Nuxt project.
```

2023-11-11 12:14 UTC, DamianGlowala commented on docs/3.api/5.kit/2.programmatic.md
> +  Overrides for the Nuxt configuration.  The alias `config` has been **Removed**
```suggestion
  Overrides for the Nuxt configuration.
```

2023-11-22 09:37 UTC, danielroe commented on docs/3.api/5.kit/2.programmatic.md
> +- `cwd` (optional)
These two parameters are both documented in the link above (https://github.com/unjs/c12).

This is meant to be a list of _additional_ options that are respected.

Instead, shall we just remove them?

2023-12-14 21:14 UTC, merged