perf: Enhance Performance with Concurrent Execution of Async Functions 🏎
nuxt/nuxt pull request #24845
Opened 2023-12-20 18:47 UTC by sanjaiyan-dev

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-12-20 21:36 UTC, GalacticHypernova commented on packages/kit/src/module/define.ts
>        await fsp.mkdir(dirname(template.dst), { recursive: true })
We can probably place this in another Promise.all that would run before the Promise.all(promises) if we want to really speed it up.

2023-12-20 21:57 UTC, GalacticHypernova commented
![image](https://github.com/nuxt/nuxt/assets/92037085/b18dd947-6fa1-4dab-bd7e-b9bc9b978725)

Appears to be a bit mixed, but I do agree that for the initial installation it would make a difference

2023-12-22 18:39 UTC, sanjaiyan-dev commented
> ![image](https://private-user-images.githubusercontent.com/92037085/292029039-b18dd947-6fa1-4dab-bd7e-b9bc9b978725.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNzAyOTIsIm5iZiI6MTcwMzI2OTk5MiwicGF0aCI6Ii85MjAzNzA4NS8yOTIwMjkwMzktYjE4ZGQ5NDctNmZhMS00ZGFiLWJkN2UtYjliYzliOTc4NzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE4MzMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOGRlYjJiOGJmZDYzZmQ3MDVkY2M1YjgzMTIzMzdjMDZhZjdlYzk1YWRjZDMzYjZmNzY4ZDdjMTEzNDk4ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7bsvW1-4NlE7HW1fdIPCzD3nkjYcEGaI_D5rNbrkmlE)
> 
> Appears to be a bit mixed with the current method being sometimes faster, but I do agree that for the initial installation it would make a difference Also, due to the similarity this has in nature to #24771 , is it possible to perhaps modify that changelog to include this? I don't mind if all credit would go to sanjaiyan and my commit would get overwritten, or if there's a way to combine them (commit1 + commit2) in the changelog, since the schema update also did this, so it would only make sense to group it in some way.

Hi @GalacticHypernova ,

Thank you for acknowledging the credit, but your contribution is more significant.
I still wonder why concurrent processing experienced a small performance drop ‽

2023-12-28 20:25 UTC, GalacticHypernova commented
> I still wonder why concurrent processing experienced a small performance drop ‽

I wouldn't count on it, it seems to give out very inaccurate reports.

2023-12-28 20:28 UTC, sanjaiyan-dev commented
> I wouldn't count on it, it seems to give out very inaccurate reports.

Understood, thank you.

2024-01-02 11:21 UTC, danielroe requested changes
we did a small benchmark on this but couldn't find that making FS access parallel was beneficial as writing to the file system generally has to be done sequentially anyway. (Though compiling the templates in parallel seems useful.)

The bit you've changed here is for Nuxt 2. The way we improved this for Nuxt 3 here:

https://github.com/nuxt/nuxt/blob/5877e11c89fa3f6cf5699ca1a96d1f8b67605f8f/packages/nuxt/src/core/app.ts#L43-L75.

I'd welcome a PR that ports that improvement to Nuxt 2 within `packages/kit/src/module/define.ts`.

(We can skip the change in `packages/nuxt/src/core/nitro.ts`.)

2024-08-12 08:50 UTC, closed without merging