docs: add eslint setup guide
nuxt/nuxt pull request #24976
Opened 2023-12-31 11:12 UTC by chris-visser

I found @antfu 's eslint package to be the best approach to enable eslint in a Nuxt project and since imho its not really clear on how to set up eslint etc in Nuxt, I've documented it. So if people agree lets add it to the docs?

2023-12-31 13:17 UTC, skmedix commented on docs/2.guide/1.concepts/9.code-style.md
> +**Add eslint.config.js to the root folder of your Nuxt app**
```suggestion
**Add `eslint.config.js` to the root folder of your Nuxt app**
```

2023-12-31 16:09 UTC, MuhammadM1998 commented
There's a WIP https://github.com/nuxt/eslint-plugin-nuxt  made by the nuxt team so I think this would be the official way.
P.S: the description says nuxt supports prettier but antfu config uses stylistic instead of prettier.

2023-12-31 16:57 UTC, huang-julien reviewed
Hello :wave:
we do have a roadmap for nuxt/eslint https://github.com/nuxt/eslint-config/issues/303
Currently i'm using `@nuxtjs/eslint-config-typescript` which works quite well i'd say

2023-12-31 21:57 UTC, antfu commented
Hey, thanks for trying!

I am working on a Nuxt module to generate a project-aware Nuxt configuration to make this easier. As the ESLint flat config is slowly becoming the standard, I believe it would make the best DX for Nuxt project.

(while me, who made my own eslint config, do believe my eslint config works pretty well ofc. It's still quite opininated to my personal taste, and might not work for every Nuxt project. It would be better to maintain a Nuxt-official version and recommend it (which we do, but there could be a lot of improvements to make for sure)).

2024-01-01 11:43 UTC, chris-visser commented
> There's a WIP https://github.com/nuxt/eslint-plugin-nuxt made by the nuxt team so I think this would be the official way. P.S: the description says nuxt supports prettier but antfu config uses stylistic instead of prettier.

I've noticed, but the last update on that package was done on 2022. I do agree though that an official package would be much better. What I find interesting though is the zero config setup of Antfu's package which is in line with Nuxt's approach to many things like the module system. 

I'm fine with anything though. Just trying to help :)

2024-01-01 13:02 UTC, MuhammadM1998 commented
@chris-visser I appreciate your help  🙏and I'm just trying to do the same didn't mean to be aggressive or something. FYI I'm using antfu's package in my project and it's indeed zero-config and it's the Nuxt way as you said. I hope that official plugin get stabilized soon!

2024-01-01 16:52 UTC, chris-visser commented
> @chris-visser I appreciate your help 🙏and I'm just trying to do the same didn't mean to be aggressive or something. FYI I'm using antfu's package in my project and it's indeed zero-config and it's the Nuxt way as you said. I hope that official plugin get stabilized soon!

Appreciate it !

2024-01-02 09:04 UTC, danielroe requested changes
Let's update this to use `@nuxt/eslint-config` for the moment. 🙏

2024-01-08 17:40 UTC, Atinux commented
Agree with @danielroe 

I do use `@nuxt/eslint-config` in most of my Nuxt projects and it works well ([example](https://github.com/Atinux/nuxt-todos-edge/blob/main/.eslintrc.cjs)).

Thank you for pushing this new page in the documentation @chris-visser ❤️

2024-01-16 11:28 UTC, danielroe commented on docs/2.guide/1.concepts/9.code-style.md
> +## Eslint
```suggestion
## ESLint
```

2024-01-16 11:28 UTC, danielroe commented on docs/2.guide/1.concepts/9.code-style.md
> +The recommended approach for Nuxt is to enable eslint using [`@nuxt/eslint-config`](https://github.com/nuxt/eslint-config).
```suggestion
The recommended approach for Nuxt is to enable ESLint support using [`@nuxt/eslint-config`](https://github.com/nuxt/eslint-config). 
```

2024-01-16 11:28 UTC, danielroe commented on docs/2.guide/1.concepts/9.code-style.md
> +Run the lint command to check if the codestyle is correct or run `lint:fix` to automatically fix issues.
```suggestion
Run the lint command to check if the code style is correct or run `lint:fix` to automatically fix issues.
```

2024-01-16 11:29 UTC, danielroe commented on docs/2.guide/1.concepts/9.code-style.md
> +description: "Nuxt 3 supports eslint out of the box"
```suggestion
description: "Nuxt supports ESLint out of the box"
```

2024-01-16 11:46 UTC, antfu approved these changes
Otherwise LGTM!

And btw, as promised, here I made a project-aware flat config generator module: https://github.com/antfu/nuxt-module-eslint-config, at some point we might make it official and mention it as the experiment support.

For better UX, I am thinking maybe this module could add an optional flag to opt-in ESLint for formatting via [ESLint Stylisttc](https://eslint.style) and [`eslint-plugin-format`](https://github.com/antfu/eslint-plugin-format) (use Prettier for HTML and CSS).

2024-01-16 11:46 UTC, antfu commented on docs/2.guide/1.concepts/9.code-style.md
> +You're good to go! On save, your files will be formatted.
```suggestion
You're good to go! On file save, your files will be lint with auto-fix.
```

We should maybe mention that `@nuxt/eslint-config` does not do auto-formatting for you, and maybe guide ppl to set up Prettier?

2024-01-16 11:46 UTC, antfu commented on docs/2.guide/1.concepts/9.code-style.md
> +    "source.fixAll.eslint": true
```suggestion
    "source.fixAll.eslint": "explicit"
```

It's updated in the latest VS Code

2024-01-16 11:46 UTC, antfu commented on docs/2.guide/1.concepts/9.code-style.md
> +  "editor.formatOnSave": true,
I am not sure if enabling this has something to do with ESLint (`codeActionsOnSave` is different from `formatOnSave`, I believe). In my own usage, I set this off to disable Prettier in favor of ESLint's auto-fix. I guess for `@nuxt/eslint-config`, we don't need to mention this line as there is no formatting involved.

```suggestion
```

2024-01-16 11:53 UTC, danielroe commented on docs/2.guide/1.concepts/9.code-style.md
> +Run the lint command to check if the code style is correct or run `lint:fix` to automatically fix issues.
```suggestion
Run the `lint` command to check if the code style is correct or run `lint:fix` to automatically fix issues.
```

2024-01-16 11:55 UTC, danielroe commented on docs/2.guide/1.concepts/9.code-style.md
> +The recommended approach for Nuxt is to enable ESLint support using [`@nuxt/eslint-config`](https://github.com/nuxt/eslint-config).
what about this @antfu?

```suggestion
The recommended approach for Nuxt is to enable ESLint support using [`@nuxt/eslint-config`](https://github.com/nuxt/eslint-config).

At the moment, this configuration will not format your files; you can set up Prettier or another tool to do so.

::alert{type=info}
We're currently working to refactor the Nuxt ESLint configuration. Subscribe to [the Nuxt ESLint roadmap](https://github.com/nuxt/eslint-config/issues/303) to follow updates.]
::
```

2024-01-16 11:56 UTC, danielroe commented on docs/2.guide/1.concepts/9.code-style.md
> +The recommended approach for Nuxt is to enable ESLint support using [`@nuxt/eslint-config`](https://github.com/nuxt/eslint-config).
what about this @antfu?

```suggestion
The recommended approach for Nuxt is to enable ESLint support using [`@nuxt/eslint-config`](https://github.com/nuxt/eslint-config).

At the moment, this configuration will not format your files; you can set up Prettier or another tool to do so.

::alert{type=info}
We're currently working to refactor the Nuxt ESLint configuration. Subscribe to [the Nuxt ESLint roadmap](https://github.com/nuxt/eslint-config/issues/303) to follow updates.]
::
```

2024-01-16 12:13 UTC, merged