perf: use `absolutePath` as cache key in `getRouteMeta`
nuxt/nuxt pull request #25514
Opened 2024-01-30 16:47 UTC by BobbieGoede

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Instead of using file contents as key, we cache the contents separately using `absolutePath` as key. While I'm not sure if there is much performance gained by not using large strings as keys, using the contents as key will add an entry on every file change, so with the current implementation the cache will keep on growing during development as old entries won't be removed. 

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

2024-01-30 16:51 UTC, danielroe requested changes
We definitely need to fix the ever-growing cache. But we can't cache based on the path as the path will stay the same even if the contents changes (e.g. if the user updates the meta and the site hot-reloads).

2024-01-30 16:56 UTC, BobbieGoede commented
> We definitely need to fix the ever-growing cache. But we can't cache based on the path as the path will stay the same even if the contents changes (e.g. if the user updates the meta and the site hot-reloads).

I know, this change uses a second cache to store the contents, if the contents have changed the metaCache entry is cleared. 

This is still indirectly using contents to cache metaCache, but doing so by caching contents by absolutePath separately. This way the keys aren't large, but the bigger gain is not having the cache grow on every change, only compared on every change.

2024-01-30 17:25 UTC, danielroe commented
Ahh. Great!

2024-01-31 22:28 UTC, BobbieGoede commented
I thought I had those flaky scroll to top tests figured out 🤦 now its failing in Ubuntu..

2024-02-04 21:26 UTC, danielroe approved these changes

2024-02-04 21:27 UTC, merged