docs: warn about `refreshNuxtData` not working with `asyncData`
nuxt/nuxt pull request #29518
Opened 2024-10-13 20:27 UTC by huang-julien

### 🔗 Linked issue
close #29368 

### 📚 Description

`refreshNuxtData` does not work with `asyncData` hook. This PR warn about it.

2024-10-13 20:32 UTC, DamianGlowala requested changes

2024-10-13 20:32 UTC, DamianGlowala commented on docs/3.api/3.utils/define-nuxt-component.md
> +Data from `useAsyncData` is only set once in the `setup` hook of your component. This means `refreshNuxtData` will not work with `asyncData`. If you need to re-run `useAsyncData`, you can change it w
```suggestion
Data from `useAsyncData` is only set once in the `setup` hook of your component. This means `refreshNuxtData` will not work with `asyncData`. If you need to re-run `useAsyncData`, you can change it with a `method` of the Options API.
```

2024-10-13 20:32 UTC, DamianGlowala commented on docs/3.api/3.utils/refresh-nuxt-data.md
> +`refreshNuxtData` only works with composition API. `asyncData` hook from the Options API does not work with `refreshNuxtData`.
```suggestion
`refreshNuxtData` only works with Composition API. `asyncData` hook from the Options API does not work with `refreshNuxtData`.
```

2024-11-28 09:49 UTC, danielroe commented on docs/3.api/3.utils/define-nuxt-component.md
> +Data from `useAsyncData` is only set once in the `setup` hook of your component. This means `refreshNuxtData` will not work with `asyncData`. If you need to re-run `useAsyncData`, you can change it w
```suggestion
Data from `asyncData` is only set once in the `setup` hook of your component. This means `refreshNuxtData` will not work with `asyncData`. If you need to re-run `useAsyncData`, you can change it with a `method` of the Options API.
```

2024-11-28 09:50 UTC, danielroe commented on docs/3.api/3.utils/define-nuxt-component.md
> +Data from `useAsyncData` is only set once in the `setup` hook of your component. This means `refreshNuxtData` will not work with `asyncData`. If you need to re-run `useAsyncData`, you can change it w
does it work to call `refreshNuxtData` later on (ie not in setup function, but in an event handler)? if so, I think we can clarify this wording slightly

2025-05-17 09:41 UTC, closed without merging