fix(docs): AsyncData typings #23114
nuxt/nuxt pull request #30349
Opened 2024-12-23 17:08 UTC by RokeAlvo

### 🔗 Linked issue

resolve #23114

### 📚 Description

The typing of AsyncData in the documentation does not match reality. The type descriptions in the documentation have been replaced with a link to GitHub

2024-12-26 18:00 UTC, cernymatej commented
I think it is helpful to see the types directly in the docs, rather than having to go to GitHub 🙏

2025-01-01 18:23 UTC, huang-julien requested changes

2025-01-01 18:23 UTC, huang-julien commented on docs/3.api/2.composables/use-async-data.md
> +[view AsyncData types on GitHub](https://github.com/nuxt/nuxt/blob/32d9e2fe740d6d8c41e729db57aa46ebad387710/packages/nuxt/src/app/composables/asyncData.ts)
This is targeting to a specific commit

2025-01-03 16:39 UTC, RokeAlvo commented on docs/3.api/2.composables/use-async-data.md
> +[view AsyncData types on GitHub](https://github.com/nuxt/nuxt/blob/32d9e2fe740d6d8c41e729db57aa46ebad387710/packages/nuxt/src/app/composables/asyncData.ts)
yes, you are right
fixed

2025-01-03 16:44 UTC, RokeAlvo commented
> I think it is helpful to see the types directly in the docs, rather than having to go to GitHub 🙏

then we just need to close the issue

2025-01-04 22:17 UTC, closed without merging

2025-01-04 22:17 UTC, danielroe commented
I'd be up for improving this or using `twoslash` to render the types, but I think we should not remove them entirely.