async validate
nuxt/nuxt pull request #3371
Opened 2018-05-24 13:39 UTC by Serjlih97

check async validate function

2018-05-24 14:21 UTC, clarkdo requested changes

2018-05-24 14:21 UTC, clarkdo commented on lib/app/server.js
> +  let validPromises = await Promise.all(Components.map((Component) => {
What's validPromises for ?

2018-05-24 14:21 UTC, clarkdo commented on lib/app/server.js
> +  let validPromises = await Promise.all(Components.map((Component) => {
The `Components` even if there is no `validate` in it will become a fast return promise, it should be duplicate, maybe you can filter out them.

2018-05-24 14:21 UTC, clarkdo commented on lib/app/server.js
> +    return Promise.all([promise])
I think `Promise.all` is not required

2018-05-24 14:39 UTC, clarkdo requested changes

2018-05-24 14:39 UTC, clarkdo commented on lib/app/server.js
> -    return Promise.all([promise])
I mean no need to use `Promise.all` 😄 , but `return promise` still necessary.

Or you can just `return promisify(Component.options.validate, app.context).then(...)`

2018-05-26 20:40 UTC, clarkdo requested changes
Thank you for your contributions😄. Please also have a look at my other previous comments.

In current implementation, if one of the `validate` failed, the others will still be executed, It seems a bit redundant and run all `validate` in parallel way may also influence each other since they share the same `app.context`.

So run all promises in sequence way might be more appropriate.
/cc @Atinux @pi0

2018-05-28 07:55 UTC, Atinux commented
Thanks for the PR.

It's a good idea, but like @clarkdo said, it's better to run the validate in series since it will avoid making useless call.

2018-05-28 18:38 UTC, pi0 commented
@Serjlih97 Thanks for this good idea. I love it.

BTW shouldn't we apply the same patch to the `client.js` file? 

https://github.com/nuxt/nuxt.js/blob/dev/lib/app/client.js#L272

Also running in series would be a better idea :)

2018-05-28 20:42 UTC, Serjlih97 commented
@pi0 How to add an additional file to this Pull Request?

2018-05-29 09:45 UTC, pi0 commented
@Serjlih97 For client.js just switch to `pr-1` branch :)

https://github.com/Serjlih97/nuxt.js/edit/patch-1/lib/app/client.js

2018-08-05 17:42 UTC, galvez commented
> How to add an additional file to this Pull Request?

Add them and just `git push` to the same branch again, GitHub will automatically update the PR. Very interested in seeing this come through @Serjlih97, thanks!

2018-08-06 20:29 UTC, Atinux commented
Need tests before merging it :)

2018-08-25 05:08 UTC, closed without merging