add https capabilities to dev server by adding `https` in nuxt config.
nuxt/nuxt pull request #3403
Opened 2018-06-01 14:17 UTC by achretien

The parameter could be `true` or options from 

https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener

2018-06-01 14:22 UTC, Alex94800 commented
+1

2018-08-01 10:56 UTC, atinux requested changes
Agree about this PR, could you add a test about it please?

2018-08-01 11:42 UTC, Atinux commented
You can add a test file called `test/unit/https.test.js` and take some inspiration from https://github.com/nuxt/nuxt.js/blob/dev/test/unit/express.test.js

The point is to test that it renders correctly on the https url and not http. And also to verify that the coverage does not decrease.

Make sure to run `npm run test:fixtures` before running `npx jest test/unit/https.test.js`.

Inside your test, you can do something like this:

```js
 const config = loadFixture('basic')
nuxt = new Nuxt(config)
port = await getPort()
await nuxt.listen(port, '0.0.0.0', /* your https options */)
```

2018-08-01 14:02 UTC, clarkdo requested changes
This feature sounds great to me, thank you for the contribution @achretien 

In my perspective, it may be not that important to add `https` in `nuxt dev`, since it's designed for development, so maybe it can be introduced in `nuxt start`.

And also, it will be better if add default value of `https` into `common/nuxt.config.js`

2018-08-01 14:02 UTC, clarkdo commented on bin/nuxt-dev
> +          return nuxt.listen(port, host, nuxtConfig.https)
Maybe unnecessary to pass `https`, config can be got through `this.options` inside `nuxt.js`

2018-08-06 11:51 UTC, zyxep commented
Why not give the developer option to run https on `nuxt dev`.
a case could be: using fb login.
Their developer platform "require" https callback urls.

some tools give devs options to create cert to e.g. localhost with e.g.
https://github.com/FiloSottile/mkcert

2018-08-29 20:35 UTC, galvez commented
Closing this as I'll push a separate forked branch from this that integrates with https://github.com/nuxt/nuxt.js/pull/3812.

2018-08-29 20:35 UTC, closed without merging