feat: add tests to check for changed files
nuxt/nuxt pull request #3893
Opened 2018-09-15 18:27 UTC by pimlie

As discussed in #3869

Make sure that if we are building or generating only files in buildDir and generate.dir are changed. If files in another location would also be changed due to a new config option, those locations should be guarded in `lib/common/options.js` so you cant set them lower then rootDir or srcDir.

## Checklist:
- [x] All new and existing tests passed.

2018-09-15 20:39 UTC, pimlie commented
Yay, all checks passed. I did a forced push with the double 'add debug logs' commits to try to remove / hide some commits as I was remotely debugging the CI failures. Either my pc is much slower or much faster then the CI's as locally the writeFile just finished long before running the tests ;)

2018-09-16 19:49 UTC, TheAlexLichter requested changes

2018-09-16 19:49 UTC, manniL commented on test/utils/build.js
> +      paths.map((item) => {
`forEach` instead of `map` if you don't need a return value.

2018-09-16 19:49 UTC, manniL commented on test/unit/basic.generate.test.js
> +    paths.map((item) => {
`forEach` instead of `map` if you don't need a return value.

2018-09-17 09:28 UTC, pimlie commented
It seems appveyor really screws up the timeout time. I was confident that using a high resolution time would be a quick fix for the waitfor test but as many times before I was wrong. Rounding the time to a whole number fixes the test in this case, but we will have to wait and see if timeouts on appveyor are off by more than 0.5ms. If so we can skip the test again, or maybe file an report with appveyor? Spent way too much on this already so actually I wouldnt mind to understand why this is at all possible ;)

2018-09-17 20:59 UTC, pi0 approved these changes
LGTM

2018-09-17 20:59 UTC, pi0 commented on test/unit/utils.test.js
> +    expect((t[0] * 1e9 + t[1]) / 1e6).not.toBeLessThan(delay - 4)
Crazy boy 😂😋

2018-09-17 21:02 UTC, TheAlexLichter approved these changes

2018-09-17 21:15 UTC, clarkdo approved these changes
LGTM

2018-09-17 21:15 UTC, clarkdo commented on test/unit/utils.test.js
> +    expect((t[0] * 1e9 + t[1]) / 1e6).not.toBeLessThan(delay - 4)
Good idea

2018-09-18 14:26 UTC, merged