chore(cli): add spa/generate warning
nuxt/nuxt pull request #4165
Opened 2018-10-21 21:30 UTC by galvez

Resolves https://github.com/nuxt/nuxt.js/issues/4036

2018-10-21 21:31 UTC, TheAlexLichter approved these changes

2018-10-21 21:31 UTC, TheAlexLichter approved these changes

2018-10-21 23:24 UTC, aldarund approved these changes

2018-10-22 00:18 UTC, aldarund approved these changes

2018-10-22 10:06 UTC, aldarund approved these changes

2018-10-22 10:27 UTC, aldarund approved these changes

2018-10-22 11:45 UTC, pi0 requested changes
Following #4019 and #4036. It seems that there are edge cases with custom baseURLs. Discouraging people from using it is not probably the best idea. Personally, use this combination in many projects without any problem. If we ever want to add this warning:

- The conditions that cause this error should be checked.  (IE, a customized baseURL is provided)
- Warning should be more precise. And probably with a short (git.io) URL refering users to the Issue or a Wiki/Docs page to explain about it.
- We have to add a TODO to resolve such edge-cases ASAP instead of telling users we know that's a issue, but get along with it for now :D

2018-10-22 22:48 UTC, manniL commented
Closed because of #4036 has been closed as well (misunderstanding)

2018-10-22 22:48 UTC, closed without merging