fix(ts): adds function type definition for `ComponentOptions.middleware`
nuxt/nuxt pull request #4531
Opened 2018-12-12 00:25 UTC by hartmut-co-uk

Better TS support: Adds function typings to `ComponentOptions.middleware`.

## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
After discussion with @kevinmarrec added type defs for functions.

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

2018-12-12 08:55 UTC, kevinmarrec requested changes

2018-12-12 08:55 UTC, kevinmarrec commented on packages/vue-app/types/vue.d.ts
> +    middleware?: string | string[] | ((ctx: Context, cb: Function) => Promise<void>| void);
Missing space around `Promise<void>|` 😇

2018-12-12 14:02 UTC, hartmut-co-uk commented on packages/vue-app/types/vue.d.ts
> +    middleware?: string | string[] | ((ctx: Context, cb: Function) => Promise<void>| void);
updated

2018-12-12 18:27 UTC, kevinmarrec requested changes
@hartmut-co-uk I think that the 2 last tests can be omitted 🤔

2018-12-12 18:30 UTC, kevinmarrec commented on test/types/index.ts
> +options.middleware = (ctx, cb) => {
Or at least we can replace it by 
```js
options.middleware = async (ctx, cb) => {}
```
to test the type
`(ctx: Context, cb: Function) => Promise<void>`
But I don't think this way will be used 😄

2018-12-12 18:31 UTC, kevinmarrec commented on test/types/index.ts
> +options.middleware = (ctx, cb) => {
The `async` way should not be used with a callback

2018-12-12 18:59 UTC, hartmut-co-uk commented
Thx @kevinmarrec
Note: after further discussion on nuxt Discord updated the PR with @kevinmarrec's final suggestion to introduce `Middleware` type + more elegant tests

2018-12-12 21:38 UTC, kevinmarrec approved these changes
Everything is perfect to me.

PR is merge-ready !

2018-12-13 23:21 UTC, galvez approved these changes
LGTM!

2018-12-14 02:31 UTC, merged