Support other implementations of Promises inside nuxtServerInit (currently only HTML5 Promises works correctly)
nuxt/nuxt pull request #456
Opened 2017-03-26 15:01 UTC by taldy

Fix for using for exapmle Axios promises in nuxtServerInit() without wrapping it to HTML5 Promise

2017-03-26 15:18 UTC, Atinux commented
Hi @taldy

Can you show an example where our code does not work?

2017-03-26 15:43 UTC, taldy commented
@Atinux

```
// store/index.js

export const actions = {
  nuxtServerInit ({ commit }) {
    return axios.get('/api/products')
      .then(res => commit(SET_PRODUCTS, res.data))
  }
}
```

2017-03-26 16:46 UTC, taldy commented
@Atinux I checked one more time and found that `async/await` solves my problem without any changes in Nuxt. 

But Vuex documentation describe returning promise from action as a legal way to use the system. That's why I thought this is a some kind of bug.

2017-04-01 05:48 UTC, any35 commented
I have same issue, maybe this code may be a better way to make sure the result is a promise. Not a object which has a property named 'then'
```
<% if (store) { %>
        let promise = (store._actions && store._actions.nuxtServerInit ? store.dispatch('nuxtServerInit', omit(getContext(context), 'redirect', 'error')) : null)
      promise = Promise.resolve(promise || undefined);
```

2017-04-05 15:34 UTC, atinux requested changes

2017-04-05 15:34 UTC, Atinux commented on lib/app/server.js
> +      if (!promise || (!(promise instanceof Promise) && (promise && typeof promise.then !== 'function'))) promise = Promise.resolve()
I believe the if can be simplify to this:
```js
if (!promise || (!(promise instanceof Promise) && typeof promise.then !== 'function'))
```

If `promise` does not pass the first check (`!promise`) it won't check the 2nd check.

Can you update this please?

2017-04-05 15:36 UTC, Atinux commented
What about updating this line as well @taldy to make every method which should return a Promise to not be only `Promise` instances? https://github.com/nuxt/nuxt.js/blob/master/lib/app/utils.js#L87

2017-04-06 07:14 UTC, any35 commented on lib/app/server.js
> +      if (!promise || (!(promise instanceof Promise) && (promise && typeof promise.then !== 'function'))) promise = Promise.resolve()
@Atinux 
axios or some other frameworks return  promise-like object, NOT a ES's Promise object. 
So the statement `promise instanceof Promise` will return `false`.
But a promise-like object behave like a promise and do works with ES's Promise object. 
Simply, just use Promise.resolve(xxx) will compatible with both promise and promise-like object
> ` promise = Promise.resolve(promise);`

BTW, to check if a object is a promise-like or not, `typeof promise.then !== 'function'`  is not enough.

2017-04-06 09:13 UTC, atinux approved these changes

2017-04-06 10:33 UTC, merged