feat(cli): opens the server listeners url in the default browser
nuxt/nuxt pull request #4930
Opened 2019-02-02 17:16 UTC by ricardogobbosouza

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Opens the server listeners url in the default browser

```bash
nuxt -o
//or
nuxt --open
````

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [ ] All new and existing tests are passing.

2019-02-02 18:08 UTC, pi0 commented
`open` package size seems good: [![install size](https://packagephobia.now.sh/badge?p=open)](https://packagephobia.now.sh/result?p=open)

2019-02-02 18:09 UTC, pi0 commented on packages/cli/src/commands/dev.js
> +      return await this._startDev(cmd, argv)
Please use named return like `const nuxt = await` + `return { nuxt }`

2019-02-02 18:35 UTC, ricardogobbosouza commented on packages/cli/src/commands/dev.js
> +      return await this._startDev(cmd, argv)
@pi0 renamed

2019-02-02 18:36 UTC, pi0 submitted a review, later dismissed

2019-02-02 18:37 UTC, ricardogobbosouza commented
@pio `opn` package was the best and most used I found

2019-02-02 18:44 UTC, pi0 commented
@ricardogobbosouza Yeah seems light-weight. The only problem I can predict is that we have the plan to try out zero dependency builds of nuxt packages. Packages that have binary files inside can be little problematic as it can't be bundled. However, my comment was general. No worries until then.

2019-02-02 18:47 UTC, kevinmarrec submitted a review, later dismissed

2019-02-02 18:53 UTC, kevinmarrec commented
Nice ! I'm wondering why [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) (that we use for the `--analyze` option of the `build`command) is using [opener](https://www.npmjs.com/package/opener) instead of [opn](https://www.npmjs.com/package/opn)

2019-02-03 06:35 UTC, pi0 commented
[opener code](https://unpkg.com/opener@1.5.1/lib/opener.js) seems has an explicit workaround for WSL and also has no binary inside it. So maybe worth comparing them?

2019-02-03 10:19 UTC, ricardogobbosouza commented
In my opinion I prefer the `opener` because it is smaller and does not contain a binary inside it.

2019-02-03 12:47 UTC, galvez submitted a review, later dismissed

2019-02-03 12:58 UTC, TheAlexLichter requested changes
Evaluate `opn` vs `opener` first.

2019-02-04 10:58 UTC, ricardogobbosouza commented
Any tips on what you guys use to compare?

2019-02-04 12:01 UTC, manniL commented
@ricardogobbosouza 

Some criterias
* Bundle Size
* System compatibility (OSX, Win, *NIX) / Interoperability
* Stability
* "Burdens" (like extra binaries)

2019-02-04 12:09 UTC, ricardogobbosouza commented
@manniL a quick comparison

https://bundlephobia.com/result?p=opn@5.4.0
https://bundlephobia.com/result?p=opener@1.5.1

`opener` is almost half the size, with no dependencies and no binaries

2019-02-04 12:10 UTC, ricardogobbosouza commented
I will change to the `opener`

2019-02-05 10:58 UTC, pimlie commented
One of the reasons opener is smaller is because opn bundles the xdg-open sh script itself. I guess thats to not to rely on the local system to have (an updated version of) xdg-open installed.

Looking at the wsl detection opn (or more specifically is-wsl) has an extra check. Unfortunately the extra dependency cannot really be used as an argument, because sindresorhus always splits his code in tiny packages and have them as deps. He claims that that increases his productiveness.

Although I am not sure what the usefulness is for us, the opn package seems to have a bit more features with the trade-off that its a bigger install size.

2019-02-05 11:12 UTC, pi0 approved these changes

2019-02-05 11:13 UTC, pi0 commented
We want something small that just works. I suggest let's try `opener`. If we found any unusual problems with it fork and improve or change to another package to prevent reinventing.

2019-02-05 11:43 UTC, Atinux commented
Actually, I believe this open should be by default on `nuxt dev` for Nuxt 3 when we will have:
- Module install with the command line = Nani?
- HMR for server parts (server middleware, etc) = Nuxt workers
- Nuxt UI that show the build progress (instead of a pending page waiting for server resources)

I am open to have it as an option at the moment, thank you @ricardogobbosouza for this PR <3

2019-02-05 11:49 UTC, ricardogobbosouza commented
@Atinux We can add as default in Nuxt 3.
Most frameworks come as standard, eg: Ionic

2019-02-05 11:58 UTC, pimlie commented
Please also keep in mind that not everybody develops on localhost. We could check for e.g. `SSH_TTY` env variable to check if somebody is logged in from remote and then not open the url by default (Because otherwise you have to close Links or lynx everytime you run nuxt dev and nobody develops their website for text-mode anyway)

2019-02-05 12:20 UTC, Atinux commented
Really good remark @pimlie

2019-02-05 13:46 UTC, TheAlexLichter approved these changes

2019-02-05 21:38 UTC, merged