fix: add type definition for configuring forkTsChecker
nuxt/nuxt pull request #5326
Opened 2019-03-21 23:46 UTC by danielroe

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Added type definition for NuxtConfiguration for new `build.typescript` option.

TypeScript validation was failing with new configuration model.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

2019-03-22 13:51 UTC, danielroe commented
I can also provide more precise types from [fork-ts-checker](https://github.com/Realytics/fork-ts-checker-webpack-plugin) docs if that would be helpful, but we'd then need to keep them in sync. I don't think they currently export the Config type, though it is present in the built npm module.

2019-03-23 02:09 UTC, kevinmarrec requested changes

2019-03-23 02:09 UTC, kevinmarrec commented on packages/config/types/build.d.ts
> +    typeCheck?: { [key: string]: string } | boolean // TBD - Couldn't find typedefs for the forkTsCheckerWebpackPlugin options
```suggestion
    typeCheck?: { [key: string]: any} | boolean // TBD - Couldn't find typedefs for the forkTsCheckerWebpackPlugin options
```

2019-03-23 02:12 UTC, kevinmarrec commented
Thanks for  your PR @danielroe !

I suggested a little change. And for the type of the options of ForkTsChecker, there is IMO too many properties to stay in sync, I prefer see if we can import it from somewhere, or see with the maintainer how we could have them.

2019-03-23 13:58 UTC, kevinmarrec requested changes

2019-03-23 13:58 UTC, kevinmarrec commented on packages/config/types/build.d.ts
>    useForkTsChecker?: { [key: string]: string } | boolean // TBD - Couldn't find typedefs for the forkTsCheckerWebpackPlugin options
```suggestion
```

`useForkTsChecker` has been removed so it needs to be removed from types.

2019-03-23 15:33 UTC, kevinmarrec requested changes

2019-03-23 15:33 UTC, kevinmarrec commented on packages/config/types/build.d.ts
> +    typeCheck?: { [key: string]: any} | boolean // TBD - Couldn't find typedefs for the forkTsCheckerWebpackPlugin options
```suggestion
    typeCheck?: { [key: string]: any } | boolean // TBD - Couldn't find typedefs for the forkTsCheckerWebpackPlugin options
```

2019-03-23 15:35 UTC, kevinmarrec commented on packages/config/types/build.d.ts
> +    typeCheck?: { [key: string]: any} | boolean // TBD - Couldn't find typedefs for the forkTsCheckerWebpackPlugin options
Oops @danielroe , could you accept this last suggestion so I can aproove the PR ? Thanks.

2019-03-24 10:49 UTC, kevinmarrec approved these changes

2019-03-24 11:02 UTC, merged

2019-03-24 11:03 UTC, pi0 commented
Thanks @danielroe @kevinmarrec :heart: