feat(types): add nuxt error type
nuxt/nuxt pull request #5950
Opened 2019-06-17 18:55 UTC by orblazer

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This add type for Nuxt error with interface `NuxtError`.
With that on error layout we can now use :
```ts
import { Component, Vue, Prop } from 'nuxt-property-decorator'
import { NuxtError } from '@nuxt/vue-app'

@Component({})
export default class ErrorPage extends Vue {
  @Prop({ required: true }) readonly error!: NuxtError;
}
```

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

2019-06-18 10:02 UTC, kevinmarrec commented
@orblazer Isn't it related to https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/types/index.d.ts#L71 ?

2019-06-18 10:09 UTC, orblazer commented
Yes @kevinmarrec we probably can merge the 2 interface et keep the name `NuxtError`

2019-06-18 15:24 UTC, kevinmarrec commented
@orblazer Alright, agreed. I would just want to know how you found the `path` property if you can link me code or documentation. Thanks in advance.

2019-06-19 09:33 UTC, orblazer commented
@kevinmarrec I have found `path` here : https://github.com/nuxt/nuxt.js/blob/31f5729828e1009a6db28fe90296c178451f9efd/packages/vue-app/template/server.js#L83

2019-06-19 09:39 UTC, kevinmarrec commented
@orblazer Alright, then I'd say we can remove `ErrorParams` in favor of  `NuxtError`. Then do
```ts
export interface NuxtError {
  message?: string
  path?: string
  statusCode?: number
}
```
> Comparing to your changes, notice `statusCode` as `number` and the alphabetical order of properties.

And also change `Context.error` signature to
```ts
error(error: NuxtError): void
```

2019-06-20 07:38 UTC, kevinmarrec requested changes

2019-06-20 07:38 UTC, kevinmarrec commented on packages/vue-app/types/index.d.ts
> +  path?: string
alphebtical order
```
message
path
statusCode
```

2019-06-20 07:55 UTC, orblazer commented on packages/vue-app/types/index.d.ts
> +  path?: string
Its good, i have miss re order property ;)

2019-06-20 08:11 UTC, kevinmarrec commented on packages/vue-app/types/index.d.ts
> +  path?: string
😁

2019-06-20 08:12 UTC, kevinmarrec approved these changes

2019-06-20 08:13 UTC, kevinmarrec commented
LGTM, thanks for the types improvement @orblazer

2019-06-24 16:56 UTC, merged