fix(types): add type definition for redirect
nuxt/nuxt pull request #6095
Opened 2019-07-19 21:23 UTC by ysfada

## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)

## Description
adds missing type definition for redirect by route name

#2421
#2432

2019-07-21 14:50 UTC, kevinmarrec requested changes
Thanks for the PR @ysfada , here is my quick review :

`RawLocation` is of type `string | Location`

It may conflicts with `redirect(path: string, query?: Route['query']): void`
I would suggest to change `RawLocation` by just `Location`, so that the new added signature for `redirect` only deal with a `Location` object.

2019-07-22 10:00 UTC, kevinmarrec approved these changes

2019-07-23 12:46 UTC, atinux approved these changes

2019-07-24 07:31 UTC, pi0 commented
Thanks for this PR @ysfada . It is fixed in 2.9 upcoming [typescript repo](https://github.com/nuxt/typescript/blob/master/packages/types/app/index.d.ts)

2019-07-24 07:31 UTC, closed without merging