fix: remove trailing slash when no subFolders are used
nuxt/nuxt pull request #6362
Opened 2019-09-04 23:01 UTC by manniL

Resolves https://github.com/nuxt-community/nuxt-i18n/issues/370

## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Checklist:
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

2019-09-05 07:08 UTC, pimlie requested changes
!! >> \_-~ #6339 ~-_ << !!

Yesterday I've spent again quite a bit of time fixing issues in nuxt/press due to slashes, it might not be a difficult thing to do but it is quite hard to track _everything_. Especially in nuxt/press where we eg dynamically create routes, routes for generating, support single prefixes for a complete module through a config option and use the same routes to create api urls pointing to json files.

This issue proves the need for such DX utilities and imo we should fix this properly before we start adding regexes to add or remove slashes everywhere.

2019-09-05 08:17 UTC, manniL commented
@pimlie I completely agree that the DX utility is a must have! If possible, could you give a more advanced statement/requirements in #6339, e.g. which user cases should be covered?

However this bug occurred also without using #6331 as described in the linked issue.

2019-09-30 08:48 UTC, pi0 commented
@pimlie @manniL Can we (for now) have this fix or prefer making refactor first?

2019-10-01 08:31 UTC, pimlie approved these changes

2019-10-08 08:46 UTC, pi0 approved these changes

2019-10-08 08:47 UTC, merged