feat(cli): display blue 'Nuxt' banner if running with TS
nuxt/nuxt pull request #6399
Opened 2019-09-11 19:27 UTC by danielroe

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
This displays blue Nuxt (vs green) in the CLI banner if Nuxt is running with TypeScript support.

Resolves: #6397

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes
   *I think that might be overkill for a simple cosmetic change*
- [x] All new and existing tests are passing.

2019-09-11 20:53 UTC, pi0 requested changes
We don't include typescript logic here. It may be better an option to customize color.

2019-09-26 12:57 UTC, danielroe commented
> We don't include typescript logic here. It may be better an option to customize color.

I've exposed a `build.ui.titleColor` option, with the idea that more ui options could be exposed in future. Is this the right location for this option? If so, I'll prepare a PR updating `@nuxt/typescript` and `@nuxt/types`.

2019-09-27 15:06 UTC, galvez requested changes
I'd call it `bannerColor` instead of `ui.titleColor`, since we don't immediately have any other options to place under that key.

2019-09-27 15:43 UTC, danielroe commented
> I'd call it `bannerColor` instead of `ui.titleColor`, since we don't immediately have any other options to place under that key.

Done!

2019-09-29 09:15 UTC, pi0 requested changes

2019-09-29 09:15 UTC, pi0 commented on packages/cli/src/utils/banner.js
> +  let bannerColor = 'green'
Please keep defaults in config package (test snapshots require update)

2019-09-30 08:45 UTC, pi0 approved these changes
LGTM! Thanks ❤️

2019-09-30 08:46 UTC, merged

2019-09-30 21:32 UTC, kevinmarrec commented
@danielroe @pi0 Is there any reason the banner border color hasn't be set to the new option ? :P

2019-09-30 21:33 UTC, kevinmarrec commented
![image](https://user-images.githubusercontent.com/25272043/65918725-a741e500-e3da-11e9-9e53-0409e4f17021.png)

2019-10-01 00:08 UTC, Exeteres commented
I have the same question :flushed:

2019-10-01 07:25 UTC, danielroe commented
@kevinmarrec @Exeteres I like the idea! (Mind you, in production mode there will be green in the picture too.)