Added information about build (SPA or SSR) into the console output
nuxt/nuxt pull request #6556
Opened 2019-10-12 13:14 UTC by knidarkness

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Resolve issue #6554 and add information about the build type which is running now.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [x] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

2019-10-14 22:01 UTC, pimlie requested changes
Thank you for your contribution!

2019-10-18 09:44 UTC, pi0 commented on packages/generator/src/generator.js
> +    consola.info(`Generating pages for your ${ssr ? 'server-rendered site' : 'SPA'}.`)
1. I agree. We don't need to pass an argument
2. It should be better to rely on `options.render.ssr`
3. I think we are always referring to this mode as `SPA` in docs. Introducing more terms makes it confusing for users IMO.

2019-11-24 06:58 UTC, galvez commented
@knidarkness do you plan on continuing work/review on this PR?

2020-03-10 14:30 UTC, Atinux commented
Rendering mode will be displayed when target PR is merged: https://github.com/nuxt/nuxt.js/pull/6159

2020-03-10 14:30 UTC, closed without merging