feat: add cors to script and preload tags
nuxt/nuxt pull request #6635
Opened 2019-10-30 14:57 UTC by hxlniada

## Types of changes

- [ x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Resolves: #6634 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

2019-10-30 16:10 UTC, pi0 requested changes

2019-10-30 16:10 UTC, pi0 commented on packages/vue-renderer/src/renderers/ssr.js
> +    scripts = scripts.replace(scriptPattern, (scriptTag, jsFile) => {
Can we refactor this functionality (parts repeated in `renderScripts` and `renderResourceHints`)

2019-10-30 16:23 UTC, clarkdo reviewed
I think replacing script for all SRR rendering is kind of expensive for app runtime.

We'd better open a pr in Vue to change `renderScripts` and `renderResourceHints`, make the support attributes, or at least delegate them in nuxt.

If you don't have enough time on it, I can open a pr and let's close this one.

2019-10-31 02:37 UTC, hxlniada commented
@clarkdo OK, I agree with you, and i do not have enough time on it

2019-10-31 11:59 UTC, clarkdo commented
Cool, I’ll work on this

2020-02-05 22:20 UTC, Austio commented
@clarkdo, this PR seems good to go but wanted to check if there was anything i can do to help get over the line and merged?  Thanks!

2020-02-06 09:02 UTC, clarkdo commented
@Austio Sorry, I’ll try to find some times to work on it this week.

2020-02-06 14:35 UTC, Austio commented
@clarkdo no need to be sorry, any way that i can help?

2020-02-06 16:28 UTC, clarkdo commented
@Austio I'll try to make a pr this week, if you can test with your app, it would be great!

2020-02-08 21:32 UTC, clarkdo commented
As Vue 2 won't be release frequently, so let's fix this issue in Nuxt for now, I'll open a new pr.

2020-02-08 21:34 UTC, closed without merging