feat: HMR support for serverMiddleware
nuxt/nuxt pull request #6881
Opened 2020-01-16 16:37 UTC by pi0

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactor

## Description

This PR brings huge DX improvements to Nuxt [serverMiddleware](https://nuxtjs.org/api/configuration-servermiddleware) by watching all serverMiddleware (and their require dependency tree).

Changes summary:
- Server refactored to support in-place HMR of middleware stack and also adds additional meta (7505ac5b7a7d9e16ec0e30023109cefbb8bc50f9)
  - New middleware syntax is more consistent with express (path/handler ~> route/handle - with backward compat support)
- Fixed an important bug in cjs helper that causes process fatal error when accessing a cache entry which had already errors (more DX coming in another PR for HMR of nuxt.config) (26581e65b9ffa9cbbe84a9e59d8d8bf83fa7fb9b)
- Replaced old full restart in Builder with new HMR in Builder (In rare cases if any error happens fullRestart fallback happens)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

2020-01-16 17:08 UTC, atinux requested changes
Small typo

2020-01-16 17:08 UTC, Atinux commented on packages/builder/src/builder.js
> +    const entires = this.nuxt.server.serverMiddlewarePaths()
```suggestion
    const entries = this.nuxt.server.serverMiddlewarePaths()
```

2020-01-16 17:08 UTC, Atinux commented on packages/builder/src/builder.js
> +    for (const entry of entires) {
```suggestion
    for (const entry of entries) {
```

2020-01-17 19:47 UTC, atinux approved these changes

2020-01-17 19:49 UTC, Atinux commented
Can we add maybe a warn for path usage? Or update the docs for serverMiddleware?

2020-01-18 11:35 UTC, pi0 commented
@Atinux Internally we normalize path/handler without any warning by this PR to use connect/express convention. We can deprecate it for Nuxt3.

2020-01-19 08:34 UTC, merged

2020-03-21 19:45 UTC, GaborTorma commented
Please update the docs woth examples, because it not working for me.
Thanx!

2020-03-23 11:36 UTC, jgmullor commented
I have the same issue as @GaborTorma, only the first change on the server middlewares is detected

2020-03-23 11:39 UTC, pi0 commented
@GaborTorma @jgmullor 

- If you are using Windows, there is a known issue going to be fixed with next release.
- This is a basic DX improvement for serverMiddleware. Nuxt functions coming soon ;)
- Would you please create an issue with reproduction steps when it is not correctly working?

2020-03-23 12:04 UTC, jgmullor commented
@pi0 in our case we're using OSX/Ubuntu, I will try to create an issue with a jsbin later today, thank you! =)

2020-03-30 12:37 UTC, HuddleHouse commented
Does anybody have an example of this working? 

I am getting this error: 

```
this.nuxt.server.serverMiddlewarePaths is not a function
```

2020-03-30 18:36 UTC, pi0 commented
@HuddleHouse Would you please ensure having 2.12+ version of `@nuxt/server` installed in `node_modules`? Are you using nuxt as middleware?

2020-03-30 22:04 UTC, HuddleHouse commented
@pi0 Thanks for responding! That helped me figure out what was wrong. 

It turns out 2.11+ versions of `@nuxt/server` & `@nuxt/core` were getting installed. I installed 2.12+ versions in dev dependencies and it worked!

2020-04-15 22:56 UTC, humanistical commented
I'm getting the below error after this change, using an Express api backend exported as below:
~/api/index.js:
import express from 'express'
...
const app = express()
...
module.exports = {
  route: '/api',
  handler: app
}

nuxt.config.js:
serverMiddleware: [{ route: '/api', handler: '~/api/index.js' }]

Error:
FATAL Cannot create property '_middleware' on string '~/api/index.js' 

at Server.resolveMiddleware (node_modules/@nuxt/server/dist/server.js:816:35) 
at Server.useMiddleware (node_modules/@nuxt/server/dist/server.js:822:36) 
at Server.setupMiddleware (node_modules/@nuxt/server/dist/server.js:680:12) 
at async Server.ready (node_modules/@nuxt/server/dist/server.js:610:5) 
at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:689:7)

2020-07-17 22:36 UTC, mobihack commented
@humanistical I am encountering the same problem. Any fix?

2020-07-18 06:13 UTC, TeleMediaCC commented
> I'm getting the below error after this change, using an Express api backend exported as below:
> ~/api/index.js:
> import express from 'express'
> ...
> const app = express()
> ...
> module.exports = {
> route: '/api',
> handler: app
> }
> 
> nuxt.config.js:
> serverMiddleware: [{ route: '/api', handler: '~/api/index.js' }]
> 
> Error:
> FATAL Cannot create property '_middleware' on string '~/api/index.js'
> 
> at Server.resolveMiddleware (node_modules/@nuxt/server/dist/server.js:816:35)
> at Server.useMiddleware (node_modules/@nuxt/server/dist/server.js:822:36)
> at Server.setupMiddleware (node_modules/@nuxt/server/dist/server.js:680:12)
> at async Server.ready (node_modules/@nuxt/server/dist/server.js:610:5)
> at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:689:7)

@mobihack 


You need to exports only the app in ~/api/index.js file:

`module.exports = app`

2020-07-18 10:23 UTC, mobihack commented
@TeleMediaCC  Thank you. This solved my problem.

For others who may encounter this problem, you don't need to sub route to '/api' inside your express setup. Just export without prepending api to your express routes.